label variable npi "National Provider Identifier"
label variable line_srvc_cnt "Number of services provided"
label variable bene_unique_cnt "Number of distinct Medicare beneficiaries"
label variable bene_day_srvc_cnt "Number of distinct Medicare beneficiary/per day services"
label variable average_medicare_allowed_amt "Average Medicare allowed amount"
label variable average_submitted_chrg_amt "Average submitted charge amount"
label variable average_medicare_payment_amt "Average Medicare payment amount"
label variable nppes_credentials "Provider credentials"
label variable nppes_provider_gender "Provider gender"
label variable nppes_entity_code "Entity type (individual or organization)"
label variable nppes_provider_state "Provider state"
label variable provider_type "Provider type"
label variable medicare_participation_indicator "Medicare participation indicator"
label variable place_of_service "Place of service (facility or non-facility)"
label variable hcpcs_code "HCPCS code"
label variable hcpcs_drug_indicator "HCPCS drug indicator"
label variable year "Year"
